dist: trusty
sudo: false
language: cpp
compiler: gcc

os: linux

services:
  - docker

before_install:
  - docker pull danoan/dipacus:env
  - docker build . -t btools:build
  
script:
  - docker run btools:build /bin/sh -c /app/scripts/test-btools.sh
